### ISSUE TITLE
Regarding the evaluation of OpenVLA on the SIMPLER simulation platform

### ISSUE THREAD

**Issue by leonwu117** [DelinQu/awesome-vision-language-action-model#1]
Dear author, first of all, I would like to sincerely thank you for summarizing and publishing your work on the current popular visual-language action models. As I am planning to conduct research based on OpenVLA, I followed your previous attempt to evaluate OpenVLA on SIMPLER. However, I found that the evaluation of OpenVLA on the Widox dataset resulted in a success rate of only 0. Therefore, I would like to ask if you have any better methods to reproduce the results presented in the OpenVLA paper, or if you have any suggestions. Relly appreciate that!

**Comment by DelinQu** [comment]
Hi! Thanks for your attention 🤗
As far as I know, openvla does not perform well on the WidowX, likely due to the camera's orientation being perpendicular to the table, which lacks geometric information such as vanishing line. Additionally, the control method in the simulation itself might differ from other environments. [xuanlinli17](https://github.com/xuanlinli17) suspects that the issue is related to data augmentation in [#issuecomment](https://github.com/simpler-env/SimplerEnv/pull/10#issuecomment-2530601918), but I think this might not be the primary cause. Recently, CogACT has achieved impressively remarkable results on simpler environments based on OpenVLA. Similarly, I'm extremely curious and would strongly suggest you submit a new issue to the [repository](https://github.com/microsoft/CogACT/issues).

**Comment by accx12** [comment]
This evaluation of OpenVLA on the SIMPLER simulation platform is really detailed and insightful. I’m curious if similar simulation approaches could be applied to optimize real-world traffic or compliance systems, like how [Simit Multas](https://simit-por-placa.co/simit-multas/) tracks and evaluates traffic violations efficiently.

**Comment by k1-ship** [comment]
This [TekChive](https://tekchive.com/) analysis of OpenVLA on the SIMPLER simulation platform is quite thorough and informative. I wonder if similar simulation methods could be used to enhance real-world traffic management or compliance systems

**Comment by aniwatch604-prog** [comment]
Aniwatch is a popular platform for anime entertainment, offering a massive collection of anime series and movies in one place. Explore the latest episodes, trending titles and classical hits across multiple genres, all available in multiple languages and with subtitles for a better watching experience. From action and adventure to fantasy, users can find all of their favourites.

https://aniwatch.tf/

**Comment by newanime-tv** [comment]
[9anime](https://9anime.tf/) Alternative is a great resource for anime lovers who want to find reliable anime streaming websites. Discover platforms with regularly updated content, high-quality video, and easy navigation, and a huge collection of anime series and movies. Enjoy your favourite anime series and movies anytime with the best streaming options available.
